Turn by turn
wtg/RPI_Tours_iOS pull request #38
Opened 2016-10-30 06:19 UTC by JohnBehnke

This should be the finalized Turn by Turn commit (hopefully)

2016-11-01 21:21 UTC, jacobspeicher requested changes
Going to a tour category hides the first tour and makes it inaccessible. The turn-by-turn itself is great, just this bug needs to be fixed.

2016-11-06 04:05 UTC, JohnBehnke commented
Hey @jacobspeicher I fixed the issue. Check it out when you get a chance.

2016-11-08 18:38 UTC, jacobspeicher approved these changes

2016-11-08 18:39 UTC, jacobspeicher commented
Aight, I approved it. Now it just has the conflicts, which I'll leave to you.

2016-11-08 19:28 UTC, merged